

```

 https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
```

Скачайте датасет pima_indians_diabetes.csv. Импортируйте его при помощи pandas в ваш Jupyter Notebook.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/pima_indians_diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
# Проверьте, есть ли пропуски в данных
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [14]:
# В качестве матрицы объект-признаки X выберите все столбцы кроме 'Outcome'
X = df.iloc[:, :-1]

In [16]:
# В качестве целевой переменной y выберите столбец 'Outcome'
y = df['Outcome']

In [17]:
# Разбейте данные на тренировочные и тестовые, установив обязательно stratify=y,
# test_size=0.2 и random_state=10 в методе train_test_split()
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size = 0.2, random_state = 10)

In [19]:
# Обучите StandardScaler на тренировочных данных и стандартизируйте тренировочные данные, после чего на обученном стандартизаторе тестовые,
# как мы делали ранее в предыдущих шагах
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [20]:
# Обучите модель логистической регрессии. Внутри модели установите параметры
#  max_iter=1000 и random_state=10
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_std, y_train)

LogisticRegression()

In [24]:
# Получите предсказания на тестовых данных в виде меток классов и вероятностей

df_coefs = pd.DataFrame(data=clf.coef_, columns=X.columns).T
df_coefs.columns = ['Coeffecient']
df_coefs

                          Coeffecient
Pregnancies                  0.510071
Glucose                      1.101216
BloodPressure               -0.216894
SkinThickness               -0.010610
Insulin                     -0.129035
BMI                          0.636238
DiabetesPedigreeFunction     0.322176
Age                          0.126741

In [27]:
y_pred = clf.predict(X_test_std)
y_pred_train = clf.predict(X_train_std)

In [29]:
# Рассчитайте метрики Precision, Recall, F1 и ROC-AUC для тестовых данных,
# округлите значений метрик до одного знака после запятой (используйте метод round())

from sklearn.metrics import precision_score, recall_score

print(f'Precision Train: {precision_score(y_train, y_pred_train)}')
print(f'Precision Test: {round(precision_score(y_test, y_pred), 1)}')

print(f'Recall Train: {recall_score(y_train, y_pred_train)}')
print(f'Recall Test: {round(recall_score(y_test, y_pred), 1)}')

Precision Train: 0.7065868263473054
Precision Test: 0.8
Recall Train: 0.5514018691588785
Recall Test: 0.7

In [30]:
from sklearn.metrics import f1_score

print(f'F1 Train: {f1_score(y_train, y_pred_train)}')
print(f'F1 Test: {round(f1_score(y_test, y_pred), 1)}')

F1 Train: 0.6194225721784777
F1 Test: 0.7

In [34]:
from sklearn.metrics import roc_auc_score

y_pred_score = clf.predict_proba(X_test_std)
y_pred_train_score = clf.predict_proba(X_train_std)

print(f'ROC-AUC Train: {roc_auc_score(y_train, y_pred_train_score[:, 1])}')
print(f'ROC-AUC Test: {round(roc_auc_score(y_test, y_pred_score[:, 1]), 1)}')

ROC-AUC Train: 0.8394626168224298
ROC-AUC Test: 0.8